package main
const (
	BITCOINMAINNET_PRIV  = "80"
	BITCOINMAINNET_PUB  = "00"
	BITCOINTESTNET_PRIV  = "EF"
	BITCOINTESTNET_PUB  = "6F"
	BYTECOINMAINNET = "92"
	BYTECOINTESTNET = "80"
	LITECOINMAINNET = "B0"
	LITECOINTESTNET = "EF"
	CHANGETHIS      = 10
)